# Generated by Django 3.1.2 on 2020-11-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
