# Generated by Django 3.1.2 on 2020-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201116_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_bids',
            name='is_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_bids',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
