# Generated by Django 3.1.2 on 2020-10-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201028_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
